# Default colors
[colors.primary]
background = '#111111'
foreground = '#EEEEEE'

# Cursor colors
[colors.cursor]
text = '#EBEBEB'
cursor = '#1f97ea'

# Normal colors
[colors.normal]
black   = '#0d0d0d'
red     = '#FF301B'
green   = '#0ec248'
yellow  = '#FFC620'
blue    = '#6f94d1'
magenta = '#b59adb'
cyan    = '#21DEEF'
white   = '#EBEBEB'

# Bright colors
[colors.bright]
black   = '#6D7070'
red     = '#FF4352'
green   = '#B8E466'
yellow  = '#FFD750'
blue    = '#1BA6FA'
magenta = '#A578EA'
cyan    = '#73FBF1'
white   = '#FEFEF8'

[window]
opacity = 0.7

# Vi mode
[[keyboard.bindings]]
key = "Space"
mods = "Control"
action = "ToggleViMode"

[colors.vi_mode_cursor]
cursor = '#FF0000'
text   = '#111111'

[colors.selection]
text = '#111111'
background = '#931b1b'